export type Product = {
  id?: number | string;
  showcaseId?: string;
  title: string;
  description: string;
  slug?: string;
  price: string;
  originalPrice?: string;
  discountPrice?: string;
  discountPercent?: number | string;
  imageUrl?: string;
  images?: string[] | unknown;
  videoUrl?: string;
  badge?: string;
  ctaLabel?: string;
  ctaHref?: string;
  active: boolean;
  isActive?: boolean;
  isFeatured?: boolean;
  isAvailable?: boolean;
  stockQuantity?: number | string;
  stockStatus?: string;
  minOrder?: number | string;
  maxOrder?: number | string | null;
  salesCount?: number | string;
  views?: number | string;
  wishlistCount?: number | string;
  ratingAverage?: number | string;
  ratingCount?: number | string;
  categoryId?: string;
  manufactureYear?: number | string | null;
  brand?: string;
  vendor?: string;
  sku?: string;
  barcode?: string;
  colorStock?: unknown;
  sortOrder: number;
};

export type Showcase = {
  id: string;
  title: string;
  active: boolean;
  mode?: string;
  autoSort?: string;
  limit?: number | string;
  categoryId?: string | null;
  manualProductIds?: Array<number | string> | unknown;
  sortOrder: number;
};

export type Banner = {
  id: string;
  title: string;
  imageUrls: string[];
  active: boolean;
  intervalSeconds?: number | string;
  heightPercent?: number | string;
  sortOrder: number;
};
