import type { BannerForm, BrandForm, CatalogLinkGroupForm, CategoryForm, ProductForm, ShowcaseForm } from "./types";

export const createShowcase = (): ShowcaseForm => ({
  id: `showcase-${Date.now()}`,
  title: "",
  active: true,
  mode: "manual",
  autoSort: "newest",
  limit: 8,
  categoryId: "",
  manualProductIds: [],
  sortOrder: 1,
});

export const createCategory = (): CategoryForm => ({
  id: `category-${Date.now()}`,
  groupId: "default-categories",
  title: "",
  slug: "",
  imageUrl: "",
  active: true,
  sortOrder: 1,
  pageSortOrder: 1,
});

export const createBrand = (): BrandForm => ({
  id: `brand-${Date.now()}`,
  groupId: "default-brands",
  title: "",
  slug: "",
  imageUrl: "",
  active: true,
  sortOrder: 1,
  homeSortOrder: 1,
});

export const createCatalogLinkGroup = (kind: "category" | "brand"): CatalogLinkGroupForm => ({
  id: `${kind}-group-${Date.now()}`,
  title: "",
  active: true,
  sortOrder: 1,
});

export const createBanner = (): BannerForm => ({
  id: `banner-${Date.now()}`,
  title: "",
  showcaseId: "",
  imageUrls: [],
  active: true,
  showOnHome: true,
  showOnShowcase: false,
  showOnCategories: false,
  showOnProducts: false,
  intervalSeconds: 5,
  heightPercent: 28,
  homeSortOrder: 1,
  showcaseSortOrder: 1,
  categorySortOrder: 1,
  productSortOrder: 1,
  sortOrder: 1,
});

export const createProduct = (): ProductForm => ({
  id: `local-${Date.now()}`,
  showcaseId: "",
  showcaseIds: [],
  title: "",
  description: "",
  slug: "",
  price: "",
  originalPrice: "",
  discountPrice: "",
  discountPercent: "",
  imageUrl: "",
  images: [],
  videoUrl: "",
  badge: "",
  ctaLabel: "مشاهده",
  ctaHref: "#",
  active: true,
  isActive: true,
  isFeatured: false,
  isAvailable: true,
  stockQuantity: 0,
  stockStatus: "in_stock",
  minOrder: 1,
  maxOrder: 0,
  weight: "",
  length: "",
  width: "",
  height: "",
  salesCount: 0,
  views: 0,
  wishlistCount: 0,
  ratingAverage: "",
  ratingCount: 0,
  discountStartAt: "",
  discountEndAt: "",
  categoryId: "general",
  categoryIds: ["general"],
  manufactureYear: "",
  brand: "",
  vendor: "",
  sku: "",
  barcode: "",
  metaTitle: "",
  metaDescription: "",
  metaKeywords: "",
  placement: "",
  publishedAt: "",
  deletedAt: "",
  colorStock: {},
  sortOrder: 1,
});
