export type ProductForm = {
  id: number | string;
  showcaseId: string;
  showcaseIds: string[];
  title: string;
  description: string;
  slug: string;
  price: string;
  originalPrice: string;
  discountPrice: string;
  discountPercent: string;
  imageUrl: string;
  images: string[];
  videoUrl: string;
  badge: string;
  ctaLabel: string;
  ctaHref: string;
  active: boolean;
  isActive: boolean;
  isFeatured: boolean;
  isAvailable: boolean;
  stockQuantity: number;
  stockStatus: string;
  minOrder: number;
  maxOrder: number;
  weight: string;
  length: string;
  width: string;
  height: string;
  salesCount: number;
  views: number;
  wishlistCount: number;
  ratingAverage: string;
  ratingCount: number;
  discountStartAt: string;
  discountEndAt: string;
  categoryId: string;
  categoryIds: string[];
  manufactureYear: string;
  brand: string;
  vendor: string;
  sku: string;
  barcode: string;
  metaTitle: string;
  metaDescription: string;
  metaKeywords: string;
  placement: string;
  publishedAt: string;
  deletedAt: string;
  colorStock: Record<string, number>;
  sortOrder: number;
};

export type ShowcaseForm = {
  id: string;
  title: string;
  active: boolean;
  mode: "manual" | "auto";
  autoSort: string;
  limit: number;
  categoryId: string;
  manualProductIds: Array<number | string>;
  sortOrder: number;
};

export type CategoryForm = {
  id: string;
  title: string;
  slug: string;
  active: boolean;
  sortOrder: number;
};

export type BannerForm = {
  id: string;
  title: string;
  imageUrls: string[];
  active: boolean;
  intervalSeconds: number;
  heightPercent: number;
  sortOrder: number;
};
