CREATE TABLE IF NOT EXISTS "AdminTheme" (
  "id" SERIAL PRIMARY KEY,
  "primary" TEXT NOT NULL DEFAULT 'gray',
  "style" TEXT NOT NULL DEFAULT 'light',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "AdminTheme"
ADD COLUMN IF NOT EXISTS "primary" TEXT NOT NULL DEFAULT 'gray';

ALTER TABLE "AdminTheme"
ADD COLUMN IF NOT EXISTS "style" TEXT NOT NULL DEFAULT 'light';

ALTER TABLE "AdminTheme"
ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "AdminTheme"
ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
